# -*- coding: utf-8 -*-
"""A/B testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfK1z-e6EI9KCby-AKv28HTsDrOhS13h

## Phase 1: Designing the Experiment (Data Generation)

Stimulation of our A/B test data. We'll create a dataset with user activity, assigning users to either a 'Control' or 'Treatment' group. Crucially, we'll program the 'Treatment' group to have a slightly better conversion rate to see if our statistical tests can detect it.
"""

import numpy as np
import pandas as pd

# --- Parameters for Data Generation ---
n_users = 10000  # Total number of fake users
control_conversion_rate = 0.10  # 10% conversion for control group
treatment_conversion_rate = 0.12  # 12% conversion for treatment group (slightly higher)

# --- Generate User IDs and Group Assignment ---
user_ids = np.arange(1, n_users + 1)
groups = np.random.choice(['Control', 'Treatment'], size=n_users, p=[0.5, 0.5]) # 50/50 split

# --- Simulate Page Views (e.g., 1 to 5 page views) ---
page_views = np.random.randint(1, 6, size=n_users)

# --- Simulate Conversions based on Group ---
converted = np.zeros(n_users, dtype=int)

for i, group in enumerate(groups):
    if group == 'Control':
        converted[i] = np.random.choice([0, 1], p=[1 - control_conversion_rate, control_conversion_rate])
    else: # Treatment group
        converted[i] = np.random.choice([0, 1], p=[1 - treatment_conversion_rate, treatment_conversion_rate])

# --- Create DataFrame ---
data = {
    'user_id': user_ids,
    'group': groups,
    'page_views': page_views,
    'converted': converted
}

df = pd.DataFrame(data)

# Display the first few rows of the generated data
print("Simulated A/B Test Data:")
display(df.head())

# Display basic stats to confirm conversion rates are different
print("\nConversion Rates by Group:")
display(df.groupby('group')['converted'].mean().reset_index())

"""## Phase 2: Exploratory Data Analysis (EDA)

Now that we have our simulated data, the next step is to perform some basic Exploratory Data Analysis. We'll start by calculating the conversion rates for both the Control and Treatment groups to get an initial understanding of the performance of each group.
"""

# Calculate conversion rates for each group
conversion_rates = df.groupby('group')['converted'].mean().reset_index()
conversion_rates.columns = ['group', 'conversion_rate']

print("Calculated Conversion Rates:")
display(conversion_rates)

# Optional: Also calculate total users and total conversions per group
summary_stats = df.groupby('group')['converted'].agg(total_users='count', total_conversions='sum').reset_index()
summary_stats['conversion_rate'] = summary_stats['total_conversions'] / summary_stats['total_users']

print("\nDetailed Group Statistics:")
display(summary_stats)

"""## Phase 3: The Statistical Test (The Core Logic)

An observed difference in conversion rates between the control and treatment groups doesn't automatically mean the new feature is better. It could be a random fluctuation. To determine if the difference is statistically significant, we'll perform a Two-Proportion Z-Test. This test will give us a Z-score and, most importantly, a P-value, which tells us the probability that the observed difference occurred by pure chance.
"""

import statsmodels.api as sm

# Extract the number of conversions and total observations for each group
n_control = summary_stats.loc[summary_stats['group'] == 'Control', 'total_users'].iloc[0]
x_control = summary_stats.loc[summary_stats['group'] == 'Control', 'total_conversions'].iloc[0]

n_treatment = summary_stats.loc[summary_stats['group'] == 'Treatment', 'total_users'].iloc[0]
x_treatment = summary_stats.loc[summary_stats['group'] == 'Treatment', 'total_conversions'].iloc[0]

# Perform the two-proportion z-test
# count = [x_control, x_treatment]
# nobs = [n_control, n_treatment]

# The function `proportions_ztest` takes counts of successes and counts of observations
z_score, p_value = sm.stats.proportions_ztest([x_control, x_treatment], [n_control, n_treatment])

print(f"Z-Score: {z_score:.3f}")
print(f"P-Value: {p_value:.3f}")

# Determine statistical significance
alpha = 0.05 # Significance level
if p_value < alpha:
    print(f"\nWith a P-value of {p_value:.3f} (which is less than {alpha}), we reject the null hypothesis.\nThis suggests that the difference in conversion rates between the Control and Treatment groups is statistically significant.")
else:
    print(f"\nWith a P-value of {p_value:.3f} (which is greater than or equal to {alpha}), we fail to reject the null hypothesis.\nThis suggests that the difference in conversion rates between the Control and Treatment groups is not statistically significant.")

"""## Phase 4: Visualization and Business Recommendation

To effectively communicate our findings, we'll visualize the conversion rates of both groups using a bar chart. Finally, we'll provide a concise business recommendation based on the statistical significance we've found.
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

# --- Re-Define Data Generation Parameters (from Phase 1) ---
n_users = 10000  # Total number of fake users
control_conversion_rate = 0.10  # 10% conversion for control group
treatment_conversion_rate = 0.12  # 12% conversion for treatment group (slightly higher)

# --- Re-Generate User IDs and Group Assignment ---
user_ids = np.arange(1, n_users + 1)
groups = np.random.choice(['Control', 'Treatment'], size=n_users, p=[0.5, 0.5])
page_views = np.random.randint(1, 6, size=n_users)
converted = np.zeros(n_users, dtype=int)

for i, group in enumerate(groups):
    if group == 'Control':
        converted[i] = np.random.choice([0, 1], p=[1 - control_conversion_rate, control_conversion_rate])
    else: # Treatment group
        converted[i] = np.random.choice([0, 1], p=[1 - treatment_conversion_rate, treatment_conversion_rate])

# --- Re-Create DataFrame ---
data = {
    'user_id': user_ids,
    'group': groups,
    'page_views': page_views,
    'converted': converted
}
df = pd.DataFrame(data)

# --- Re-Calculate Conversion Rates and Summary Stats (from Phase 2) ---
conversion_rates = df.groupby('group')['converted'].mean().reset_index()
conversion_rates.columns = ['group', 'conversion_rate']
summary_stats = df.groupby('group')['converted'].agg(total_users='count', total_conversions='sum').reset_index()
summary_stats['conversion_rate'] = summary_stats['total_conversions'] / summary_stats['total_users']

# --- Re-Perform Two-Proportion Z-Test (from Phase 3) ---
n_control = summary_stats.loc[summary_stats['group'] == 'Control', 'total_users'].iloc[0]
x_control = summary_stats.loc[summary_stats['group'] == 'Control', 'total_conversions'].iloc[0]
n_treatment = summary_stats.loc[summary_stats['group'] == 'Treatment', 'total_users'].iloc[0]
x_treatment = summary_stats.loc[summary_stats['group'] == 'Treatment', 'total_conversions'].iloc[0]
z_score, p_value = sm.stats.proportions_ztest([x_control, x_treatment], [n_control, n_treatment])

# Set a style for the plots
sns.set_style("whitegrid")

# Create a bar chart of conversion rates
plt.figure(figsize=(8, 6))
sns.barplot(x='group', y='conversion_rate', data=conversion_rates, hue='group', palette='viridis', legend=False)

plt.title('Conversion Rates by Group (Control vs. Treatment)')
plt.xlabel('Group')
plt.ylabel('Conversion Rate')
plt.ylim(0, max(conversion_rates['conversion_rate']) * 1.2) # Set y-axis limit for better visualization

# Add the conversion rate percentages on top of the bars
for index, row in conversion_rates.iterrows():
    plt.text(index, row['conversion_rate'] + 0.005, f"{row['conversion_rate']:.2%}",
             color='black', ha="center", va='bottom')

plt.show()

# Business Recommendation based on P-value
alpha = 0.05 # Significance level

print("\n--- Business Recommendation ---")
if p_value < alpha:
    print(f"The A/B test results indicate a statistically significant difference in conversion rates between the Control and Treatment groups (P-value = {p_value:.3f}). ")
    print(f"The Treatment group achieved a conversion rate of {conversion_rates.loc[conversion_rates['group'] == 'Treatment', 'conversion_rate'].iloc[0]:.2%}, which is higher than the Control group's {conversion_rates.loc[conversion_rates['group'] == 'Control', 'conversion_rate'].iloc[0]:.2%}. ")
    print("Therefore, we recommend implementing the new feature/change introduced to the Treatment group, as it is proven to positively impact conversion rates.")
else:
    print(f"The A/B test results do not show a statistically significant difference in conversion rates between the Control and Treatment groups (P-value = {p_value:.3f}). ")
    print("The observed difference could be due to random chance. Therefore, we do not recommend implementing the new feature/change based on these results without further investigation or a larger sample size.")